spring:
  servlet:
    multipart:
        maxFileSize: 300MB
        maxRequestSize: 300MB
  thymeleaf:
    cache: false
      # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/templates/
    # 这个可以不配置，检查模板位置
    # 下面3个不做解释了，可以不配置
    suffix: .html
    encoding: UTF-8
    # 模板的模式
    mode: HTML